[common]
server_addr=YOUR_NPS_SERVER
server_port=8024
vkey=YOUR_NPS_VKEY
auto_reconnection=true

[xiaozhi-ws]
mode=tcp
target_addr=127.0.0.1:8031
server_port=18031

[xiaozhi-console]
mode=tcp
target_addr=127.0.0.1:8032
server_port=18032

[xiaozhi-http]
mode=tcp
target_addr=127.0.0.1:8033
server_port=18033
