[common]
server_addr=YOUR_NPS_SERVER
server_port=8024
vkey=YOUR_NPS_VKEY
auto_reconnection=true

[xiaozhi-ws]
mode=tcp
target_addr=10.11.19.58:8041
server_port=18041

[xiaozhi-console]
mode=tcp
target_addr=10.11.19.58:8042
server_port=18042

[xiaozhi-http]
mode=tcp
target_addr=10.11.19.58:8043
server_port=18043
